name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - dev1
      - dev2
      - master
      - skytube
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

        # See gradle file for difference between downloaders
      - name: Build and run Tests
        run: |
          if [[ "$GITHUB_EVENT_NAME" == 'schedule' ]]; then
            echo running with real downloader
            ./gradlew check --stacktrace -Ddownloader=REAL
          else
            echo running with mock downloader
            ./gradlew check --stacktrace -Ddownloader=MOCK
          fi
